-- Pura Ruta Guide: ejecutar en Supabase > SQL Editor.
-- Es seguro ejecutarlo más de una vez (idempotente).

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'visitor' check (role in ('visitor', 'business_pending', 'business_verified', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  description text,
  category text,
  address text,
  province text,
  canton text,
  district text,
  latitude numeric,
  longitude numeric,
  phone text,
  whatsapp text,
  email text,
  website text,
  image_url text,
  budget_level text check (budget_level is null or budget_level in ('bajo', 'medio', 'premium')),
  is_active boolean not null default true,
  is_verified boolean not null default false,
  verification_status text not null default 'pending' check (verification_status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, business_id)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  body text not null check (char_length(body) between 3 and 1000),
  moderation_status text not null default 'published' check (moderation_status in ('published', 'hidden', 'pending')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

-- Si la tabla businesses ya existía con el schema anterior, agrega las columnas que usa la app.
alter table public.businesses add column if not exists category text;
alter table public.businesses add column if not exists province text;
alter table public.businesses add column if not exists canton text;
alter table public.businesses add column if not exists district text;
alter table public.businesses add column if not exists image_url text;
alter table public.businesses add column if not exists budget_level text;
alter table public.businesses add column if not exists is_active boolean not null default true;
alter table public.businesses add column if not exists is_verified boolean not null default false;
alter table public.businesses add column if not exists verification_status text not null default 'pending';
alter table public.businesses add column if not exists whatsapp text;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.businesses enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Perfiles públicos para usuarios autenticados" on public.profiles;
drop policy if exists "Usuario crea su perfil" on public.profiles;
drop policy if exists "Usuario actualiza su perfil" on public.profiles;
drop policy if exists "Categorías visibles" on public.categories;
drop policy if exists "Negocios verificados visibles" on public.businesses;
drop policy if exists "Propietario crea su negocio" on public.businesses;
drop policy if exists "Propietario actualiza su negocio" on public.businesses;
drop policy if exists "Usuario consulta favoritos propios" on public.favorites;
drop policy if exists "Usuario agrega favoritos propios" on public.favorites;
drop policy if exists "Usuario elimina favoritos propios" on public.favorites;
drop policy if exists "Reseñas publicadas visibles" on public.reviews;
drop policy if exists "Usuario crea su reseña" on public.reviews;
drop policy if exists "Usuario actualiza su reseña" on public.reviews;

create policy "Perfiles públicos para usuarios autenticados" on public.profiles
  for select to authenticated using (true);
create policy "Usuario crea su perfil" on public.profiles
  for insert to authenticated with check (auth.uid() = id);
create policy "Usuario actualiza su perfil" on public.profiles
  for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Categorías visibles" on public.categories
  for select to anon, authenticated using (true);
create policy "Negocios verificados visibles" on public.businesses
  for select to anon, authenticated using (
    owner_id = auth.uid()
    or (
      coalesce(is_active, true) = true
      and (
        coalesce(is_verified, false) = true
        or verification_status = 'verified'
      )
    )
  );
create policy "Propietario crea su negocio" on public.businesses
  for insert to authenticated with check (owner_id = auth.uid());
create policy "Propietario actualiza su negocio" on public.businesses
  for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "Usuario consulta favoritos propios" on public.favorites
  for select to authenticated using (auth.uid() = user_id);
create policy "Usuario agrega favoritos propios" on public.favorites
  for insert to authenticated with check (auth.uid() = user_id);
create policy "Usuario elimina favoritos propios" on public.favorites
  for delete to authenticated using (auth.uid() = user_id);
create policy "Reseñas publicadas visibles" on public.reviews
  for select to anon, authenticated using (moderation_status = 'published' or auth.uid() = user_id);
create policy "Usuario crea su reseña" on public.reviews
  for insert to authenticated with check (auth.uid() = user_id);
create policy "Usuario actualiza su reseña" on public.reviews
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.categories (name, icon) values
  ('Hospedaje', '🏨'),
  ('Tours', '🥾'),
  ('Atracciones', '◈'),
  ('Termales', '♨️'),
  ('Restaurante', '🍽️'),
  ('Cafés', '☕'),
  ('Transporte', '🚐'),
  ('Renta', '🚗'),
  ('Comercio', '🛍️'),
  ('Bienes Raíces', '🏠')
on conflict (name) do nothing;

insert into storage.buckets (id, name, public)
values ('business-photos', 'business-photos', true)
on conflict (id) do nothing;

drop policy if exists "Fotos de negocio visibles" on storage.objects;
drop policy if exists "Usuarios autenticados suben fotos de negocio" on storage.objects;
drop policy if exists "Dueño actualiza su foto de negocio" on storage.objects;
drop policy if exists "Dueño elimina su foto de negocio" on storage.objects;

create policy "Fotos de negocio visibles"
on storage.objects for select
to public
using (bucket_id = 'business-photos');

create policy "Usuarios autenticados suben fotos de negocio"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'business-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Dueño actualiza su foto de negocio"
on storage.objects for update
to authenticated
using (
  bucket_id = 'business-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'business-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Dueño elimina su foto de negocio"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'business-photos'
  and auth.uid()::text = (storage.foldername(name))[1]
);
